# config/_default/languages.en.toml

languageCode = "en"
languageName = "English"

title = "Guanran928's blog."
copyright = "Â© 2024 Guanran928, licensed under [CC-BY-SA-4.0](https://creativecommons.org/licenses/by-sa/4.0/)"

[params.author]
name = "Guanran928"
image = "img/author.png"
links = [
  # id
  # or "https://github.com/Guanran928.gpg"
  { gpg = "https://git.ny4.dev/nyancat.gpg" },
  { email = "mailto:guanran928@outlook.com" },
  { matrix = "https://matrix.to/#/@nyancat:ny4.dev" },
  { telegram = "https://t.me/guanranwang" },

  # dev
  { forgejo = "https://git.ny4.dev/nyancat" },
  { github = "https://github.com/Guanran928" },

  # social
  { mastodon = "https://mastodon.ny4.dev/@nyancat" },
  { x-twitter = "https://x.com/Guanran928" },

  # misc
  { lastfm = "https://www.last.fm/user/Guanran928" },
  { monkeytype = "https://monkeytype.com/profile/Guanran928" },
  { steam = "https://steamcommunity.com/profiles/76561198855505856" },
]
